# Uncomment the next line to define a global platform for your project


target 'ExamenMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExamenMobile
   pod 'Alamofire'
  pod 'Starscream', '~> 3.0.2'
   pod 'SwiftyJSON'
  pod 'MBProgressHUD', '~> 1.1.0'
end
